### ISSUE TITLE
Trying to load openapi 3.0 file produces error

### ISSUE THREAD

**Issue by madonius** [aress31/swurg#75] opened 2022-02-01 12:53 UTC
When trying to import [this](https://gist.githubusercontent.com/odevodyssey/c4fcbb410fde3bc9fbabcbef1e7eda15/raw/593990c8957c3b30f5909ee6eab3f8a436d0caa4/createAPIExample.yml) file to the openapi parser, I get
```
Cannot invoke: "String.equals(Object)" because the return value of "java.net.URI.getSchreme()" is null.
```
I have the same issue with a non-public openapi definition.

**Comment by aress31** [comment] 2022-03-04 23:39
Finally found time to take a look at this ticket. I can confirm that this is not a bug, your file is not getting parsed by design. Indeed, your API spec lacks a `scheme` field as clearly stated in the error message, this is a valid `OpenAPI v3 scheme in YAML`:
```yaml
servers:
  - url: http://petstore.swagger.io/v1
```

As mentioned, many times already, `OpenAPI parser` is very strict when it comes to the syntax and closely follows the `OpenAPI standard`. Therefore, you need to provide all the **mandatory fields**.

See the following for a working `YAML` example:
- https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml

The above example works just fine with `OpenAPI Parser`.

Hope this help, I am now closing this ticket.

**Closed by aress31** 2022-03-04 23:39 UTC
Labels: bug
